Claims/Models/ErrorViewModel.cs
using System;

namespace Claims.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Claims/Controllers/ClaimsController.cs
using Claims.AuthorizationAttributes;
using Microsoft.AspNetCore.Mvc;

namespace Claims.Controllers
{
    public class ClaimsController : Controller
    {
        public IActionResult Index() => View();

        [YearsWorked(2)]
        public IActionResult TwoYearRewards() => View();

        [YearsWorked(5)]
        public IActionResult FiveYearRewards() => View();

        [YearsWorked(10)]
        public IActionResult TenYearRewards() => View();
    }
}

Claims/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Claims.Models;

namespace Claims.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Claims/Controllers/PolicyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Claims.Controllers
{

    public class PolicyController : Controller
    {
        public IActionResult Index() => View();

        [Authorize(Policy = "WorkedTwoYears")]
        public IActionResult TwoYearRewards() => View();

        [Authorize(Policy = "WorkedFiveYears")]
        public IActionResult FiveYearRewards() => View();

        [Authorize(Policy = "WorkedTenYears")]
        public IActionResult TenYearRewards() => View();
    }
}

Claims/Views/Claims/FiveYearRewards.cshtml
<h1>Five Years</h1>

Claims/Views/Claims/Index.cshtml
<h1>Index</h1>


<h3>User Claims</h3>
<ul>
    @foreach (var claim in User.Claims)
    {
        <li>@claim.Type - @claim.Value</li>
    }
</ul>
<a asp-controller="Claims" asp-action="TwoYearRewards">Two Years</a> <br />
<a asp-controller="Claims" asp-action="FiveYearRewards">Five Years</a> <br />
<a asp-controller="Claims" asp-action="TenYearRewards">Ten Years</a>

Claims/Views/Claims/TenYearRewards.cshtml
<h1>Ten Years</h1>

Claims/Views/Claims/TwoYearRewards.cshtml
<h1>Two Years</h1>

Claims/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Claims/Views/Policy/FiveYearRewards.cshtml
<h1>Five Years</h1>

Claims/Views/Policy/Index.cshtml
<h1>Index</h1>


<h3>User Claims</h3>
<ul>
    @foreach (var claim in User.Claims)
    {
        <li>@claim.Type - @claim.Value</li>
    }
</ul>
<a asp-controller="Policy" asp-action="TwoYearRewards">Two Years</a> <br />
<a asp-controller="Policy" asp-action="FiveYearRewards">Five Years</a> <br />
<a asp-controller="Policy" asp-action="TenYearRewards">Ten Years</a>

Claims/Views/Policy/TenYearRewards.cshtml
<h1>Ten Years</h1>

Claims/Views/Policy/TwoYearRewards.cshtml
<h1>Two Years</h1>

Claims/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Claims</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Claims</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Claims" asp-action="Index">Claims Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Policy" asp-action="Index">Policy Test</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Claims - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>